name: School Monitor

on:
  schedule:
    - cron: "5 8 * * *"   # 11:05 Българско време (UTC+3)
    - cron: "5 13 * * *"  # 16:05 Българско време (UTC+3)
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python monitor.py
